language: python
python: "2.7"
branches:
    only:
        - master
install:
    - "pip install -r test_requirements.txt"
script:
    - "pep8 django_html5validator"
    - "nosetests -v --with-coverage --cover-package=django_html5validator"
